name: Forex Scanner Schedule

on:
  schedule:
    - cron: "0 0-18 * * 1-5"  # Every hour 00:00-18:00 UTC Mon-Fri
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas numpy pytz statsmodels scikit-learn pandas_ta==0.3.14b0
        sudo apt-get install -y libatlas-base-dev  # Fix for numpy issues

    - name: Run Enhanced Scanner
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
        GOLDAPI_KEY: ${{ secrets.GOLDAPI_KEY }}
      run: |
        python scanner.py
