name: Forex Scanner Schedule

on:
  schedule:
    # Run every hour from Mon 00:00 to Fri 18:00 UTC (matches UK time)
    - cron: "0 0-18 * * 1-5"
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas numpy pytz statsmodels scikit-learn
        # Install specific version of pandas_ta that works
        pip install pandas-ta==0.3.14b0

    - name: Run Enhanced Scanner
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
        GOLDAPI_KEY: ${{ secrets.GOLDAPI_KEY }}
      run: |
        python scanner.py
