name: Football Scanner

on:
  schedule:
    # Runs at 3 AM UK time every day (adjusts for BST/GMT automatically)
    - cron: '0 3 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scanner
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          FOOTBALL_DATA_TOKEN: ${{ secrets.FOOTBALL_DATA_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python scanner.py

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Scanner run failed',
              body: 'The scheduled football scanner run failed. Check the logs for details.'
            })
